### ISSUE TITLE
I encountered a HTTPNotFound error

### ISSUE THREAD

**Issue by hao-lee** [0xKD/pretty-mailing-list#5]
Hello, I encountered this exception. Seems weird.
```
[2022-03-29 10:34:13 +0800] [25173] [INFO] Starting gunicorn 20.1.0
[2022-03-29 10:34:13 +0800] [25173] [INFO] Listening at: http://127.0.0.1:8000 (25173)
[2022-03-29 10:34:13 +0800] [25173] [INFO] Using worker: sync
[2022-03-29 10:34:13 +0800] [25187] [INFO] Booting worker with pid: 25187
[2022-03-29 10:34:38 +0800] [25187] [ERROR] Error handling request /view?src=https%3A%2F%2Flore.kernel.org%2Flinux-nfs%2F20210407001658.2208535-1-pakki001%40umn.edu%2F
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Library/Python/3.8/site-packages/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/Library/Python/3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Library/Python/3.8/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/Library/Python/3.8/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/Library/Python/3.8/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/Library/Python/3.8/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/Library/Python/3.8/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/Library/Python/3.8/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/Library/Python/3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/Library/Python/3.8/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/Library/Python/3.8/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/Library/Python/3.8/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/Library/Python/3.8/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/Library/Python/3.8/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/Library/Python/3.8/site-packages/pyramid/viewderivers.py", line 141, in _requestonly_view
    response = view(request)
  File "/Users/didi/pretty-mailing-list-master/src/pml/views/home.py", line 40, in view_thread
    thread = render_thread(src)
  File "/Users/didi/pretty-mailing-list-master/src/pml/utils/listparser.py", line 346, in render_thread
    cached = get_cached_content(redis_client, message_id)
  File "/Users/didi/pretty-mailing-list-master/src/pml/utils/listparser.py", line 336, in get_cached_content
    root_message_id = redis_client.get(message_id)
  File "/Library/Python/3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Library/Python/3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Library/Python/3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Library/Python/3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
[2022-03-29 10:35:08 +0800] [25173] [CRITICAL] WORKER TIMEOUT (pid:25187)
[2022-03-29 10:35:08 +0800] [25187] [INFO] Worker exiting (pid: 25187)
[2022-03-29 10:35:08 +0800] [29161] [INFO] Booting worker with pid: 29161
```

**Comment by 0xKD** [comment]
You need redis running on localhost:6379. Right now it is a hard dependency (for caching purpose)

**Comment by hao-lee** [comment]
Thanks.
